version: "3.8"

services:
  app:
    build: .
    expose:
      - "8000"   
    restart: always
    deploy:
      replicas: 3


  nginx:
    image: nginx:latest
    ports:
      - "8000:80"  # Map NGINX port 80 to host port 8000
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app
    restart: always
