name: Trigger auto deployment for mlops-api

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/mlops-api-AutoDeployTrigger-e041997b-e1a0-4202-9532-e574472ef69d.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.MLOPSAPI_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.MLOPSAPI_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.MLOPSAPI_AZURE_SUBSCRIPTION_ID }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pylint pytest

      - name: Lint with pylint
        run: |
          pylint src/ || true

      - name: Run unit tests with coverage
        run: |
          pytest --cov=src --cov-report=term-missing --cov-report=xml

      - name: Upload coverage report as artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage.xml

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          dockerfilePath: ./Dockerfile  # Correct key and relative path
          registryUrl: mlopsarij.azurecr.io
          registryUsername: ${{ secrets.MLOPSAPI_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.MLOPSAPI_REGISTRY_PASSWORD }}
          containerAppName: mlops-api
          resourceGroup: mlops-rg
          imageToBuild: mlopsarij.azurecr.io/mlops-api:${{ github.sha }}

      - name: Print deployment success
        run: echo "Deployment to Azure Container Apps was successful!"


